<a href="https://colab.research.google.com/github/blackartus/FrequencyWords/blob/master/typyDanych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Typy Danych

In [3]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [5]:
A = np.array([1.5,2.4,3], dtype='float32')
A.dtype

dtype('float32')

In [6]:
A = np.array([1.5,2.4,3], dtype='complex')
A.dtype

dtype('complex128')

In [7]:
print(A)

[1.5+0.j 2.4+0.j 3. +0.j]


In [8]:
A = np.array([1.5,2.4,3], dtype='int')
A.dtype

dtype('int64')

In [9]:
A

array([1, 2, 3])

In [10]:
A = np.array([True, False])
A

array([ True, False])

In [11]:
A.dtype

dtype('bool')

In [13]:
A = np.array([24,120,230], dtype=np.int8)
A


array([ 24, 120, -26], dtype=int8)

In [14]:
A = np.array([24,120,230], dtype=np.uint8)
A

array([ 24, 120, 230], dtype=uint8)